# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/mycrocast/iOS-SDK-Podspec.git'

target 'SDKTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MycrocastSDK'
  # Pods for SDKTest

  target 'SDKTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SDKTestUITests' do
    # Pods for testing
  end

end
